version: 2
jobs:
    build:
      machine:
        image: ubuntu-2004:202008-01
      steps:
        - checkout
        - run:
           name: Build Peridigm
           command: |
              docker build . -t peridigm/peridigm
              docker images
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages